### PR TITLE
Ensure ACL configuration option is set during activation

### PR DESCRIPTION
**Pull request by elidupuis**
Previously the ACL would always default to 'public-read' because the
option was not passed.

See https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index/blob/master/lib/s3.js#L75

### CODE REVIEW

**Comment by ghedamat** [comment]
LGTM! I believe we don't have a test for the `index.js` of this repo and it seems 
that testing "setting"  the  ACL options was already done
https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index/blob/master/tests/unit/lib/s3-nodetest.js#L301-L311

@elidupuis I guess we can remove the default at https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index/blob/master/lib/s3.js#L75 as the one from config will now be used https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index/blob/master/index.js#L18

@LevelbossMike or @lukemelia let us know if you have further comments (I'm not super familiar with this plugin :) )

**Comment by elidupuis** [comment]
Thanks @ghedamat!

I've removed the default ACL as suggested (and updated the test accordingly).

**Comment by lukemelia** [comment]
Thanks @elidupuis. Please squash this and we'll get it merged!

**Comment by elidupuis** [comment]
Squashed and ready to go, @lukemelia!

**Comment by ghedamat** [comment]
thanks @elidupuis !

**Pull request merged**
