### PR TITLE
Fixes S3 redirection rule to use 404

### PR DESCRIPTION
**Pull request by jpaas**
I believe that the redirection rule should redirect on a 404 rather than a 403

### CODE REVIEW

**Comment by achambers** [comment]
I'll leave this one to @LevelbossMike

**Comment by LevelbossMike** [comment]
I changed this to 403 because I got a 403 instead of a 404 when trying to access a revision via its key directly (i.e. `<your-endpoint-address>/index.html:<sha>`) or when I tried to access a route like `<your-endpoint-address>/about`. Do you see a different response from S3?

I am using the Ireland region. Is this different across regions? Can you please tell me more about your bucket setup?

**Comment by jpaas** [comment]
My redirect config used a 404 before when I was using the original ember-deploy-s3-index adapter. After migrating to ember-cli-deploy-s3-index, I switched it to 403 according to the instructions, but it wouldn't work until I switched it back to 404.

My bucket is the the us-west-2 region, uses a bucket policy like:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::mydomain.com/*"
        }
    ]
}
```

and a redirection rule like:

```
<RoutingRules>
    <RoutingRule>
        <Condition>
            <HttpErrorCodeReturnedEquals>404</HttpErrorCodeReturnedEquals>
        </Condition>
        <Redirect>
            <ReplaceKeyPrefixWith>#/</ReplaceKeyPrefixWith>
        </Redirect>
    </RoutingRule>
</RoutingRules>
```

**Comment by LevelbossMike** [comment]
thx. I'll look into this later today why I am getting a 403 and you are getting a 404. Suppose it's the bucket policy. we could specify both redirection rules in the README though. just to be sure to catch all cases. What I think would also be great is to include a generator that sets up a bucket with the right settings (not sure if this is possible)

**Comment by LevelbossMike** [comment]
This seems to be bucket policy related. As far as I understand when the public is not allowed to list all contents of a bucket you will receive a 403 instead of a 404.

https://forums.aws.amazon.com/message.jspa?messageID=210268#210268

I am not quite sure how to proceed here. When creating a bucket with the default options you will get a 403. Do we want to advocate a puplic list access for everyone (I tend to disagree)? We can put a note about this behaviour in the README. What's your opinion on this @jpaas ?

**Comment by jpaas** [comment]
The explanation of when a 403 happens vs a 404 makes sense to me, but for some reason my bucket does not behave that way.  My bucket policy listed above does not give ListObject permission, only GetObject, exactly like the guy who started that thread on the AWS forum. So I would expect to get 403s like him, but I'm getting 404s. I'll continue to try and find an explanation.

**Comment by jpaas** [comment]
The more I look into this, I believe my bucket is misbehaving by returning a 404 instead of a 403. I just haven't figured out why yet. Also, returning a 403 is the desirable behaviour, so I no longer believe this pull request should be integrated.

**Comment by achambers** [comment]
Okie doke.....Thanks for chatting through this folks. I'm closing as per @jpaas' comment.

**Pull request closed without merging**
